from __future__ import annotations

import asyncio
import json
import logging
import re
from pathlib import Path

import google.generativeai as genai
from pydantic import ValidationError

from app.core.config import settings
from app.schemas.content import GeneratedContent


logger = logging.getLogger("app.ai")


class AIServiceError(Exception):
    pass


class AIService:
    def __init__(self) -> None:
        self.model_name = settings.GEMINI_MODEL
        self.request_timeout = settings.GEMINI_REQUEST_TIMEOUT

    def _ensure_configured(self) -> None:
        if not settings.GEMINI_API_KEY:
            raise AIServiceError("GEMINI_API_KEY is not configured.")
        genai.configure(api_key=settings.GEMINI_API_KEY)

    async def generate_content(
        self, text_content: str, user_id: str, filename: str | None = None
    ) -> GeneratedContent:
        self._ensure_configured()

        prompt = self._build_prompt(text_content, filename)
        gen_cfg = genai.GenerationConfig(response_mime_type="application/json")

        def _call() -> str:
            model = genai.GenerativeModel(self.model_name, generation_config=gen_cfg)
            resp = model.generate_content(
                prompt,
                request_options={"timeout": self.request_timeout},
            )
            if not resp.text:
                raise AIServiceError("No content generated by AI.")
            return resp.text

        try:
            raw = await asyncio.to_thread(_call)
        except Exception as exc:
            logger.exception("ai_generate_failed", extra={"user_id": user_id})
            raise AIServiceError(str(exc)) from exc

        raw = raw.strip()
        if raw.startswith("```"):
            raw = re.sub(r"^```(?:json)?\s*", "", raw)
            raw = re.sub(r"\s*```$", "", raw)

        try:
            parsed = json.loads(raw)
            return GeneratedContent(**parsed)
        except json.JSONDecodeError as exc:
            logger.error("ai_json_decode_error", extra={"raw": raw[:2000], "user_id": user_id})
            raise AIServiceError("AI response is not valid JSON.") from exc
        except ValidationError as exc:
            logger.error("ai_validation_error", extra={"user_id": user_id})
            raise AIServiceError(f"AI response validation error: {exc}") from exc

    def _build_prompt(self, text_content: str, filename: str | None) -> str:
        name = filename or "document"
        return f"""You are an expert in educational content creation. Analyze the lecture text below (source file name hint: "{name}").

You MUST respond with a single valid JSON object only (no markdown fences, no prose outside JSON) with exactly these keys:
- "summary": string, structured Markdown (use headings ##/###, bullet lists where helpful) suitable as a study note.
- "title": string, short human-readable title for the lecture (infer from content if needed).
- "quiz": array of 5 to 12 objects, each with:
    - "question": string
    - "options": array of exactly 4 distinct strings (the multiple-choice answers)
    - "correct_index": integer 0-3 (index into "options")
    - "explanation": optional string

Rules:
- "options" length must always be 4.
- "correct_index" must reference the correct option.
- Base everything strictly on the provided text.

Text:
---
{text_content}
---
"""


def offline_placeholder_content(text: str, filename: str | None) -> GeneratedContent:
    stem = Path(filename).stem if filename else "document"
    cap = 100_000
    snippet = text[:cap]
    if len(text) > cap:
        snippet += "\n\n…"
    summary = (
        "## Конспект без ИИ\n\n"
        "Переменная **GEMINI_API_KEY** не задана — Gemini не вызывался. "
        "Ниже текст, извлечённый из PDF.\n\n"
        f"### Текст\n\n{snippet}\n"
    )
    return GeneratedContent(title=stem, summary=summary, quiz=[])


def get_ai_service() -> AIService:
    return AIService()
